#%RAML 1.0
title: lm-sfdc-sapi1
mediaType: [application/json,application/xml]
protocols: [HTTP,HTTPS]
version: v1
description: This is the API which provides the Customer data and order data
uses:
  coreLib: exchange_modules/9401a589-a992-4678-9f6b-f2f639e22832/core-api-library/1.0.1/core-api-lib.raml
  dataTypeLib:  exchange_modules/9401a589-a992-4678-9f6b-f2f639e22832/core-api-library1/1.0.3/core-api-library1.raml

/Customers:
  post:
    is: [coreLib.clientIdRequired,coreLib.needsCorrelationId]
    displayName: create New customer
    description: To create a new customer
    body:
      type: dataTypeLib.customer
      examples: !include exchange_modules/9401a589-a992-4678-9f6b-f2f639e22832/core-api-library1/1.0.3/example/customerData-example.raml
    responses:
      201:
        body:
          type: object
          example:
            {
              message: "Created"
            }
            
      400:
        body:
          application/json:
            type: coreLib.errorResponseType
            examples: !include exchange_modules/9401a589-a992-4678-9f6b-f2f639e22832/core-api-library/1.0.1/examples/api-client-failure-response-example.raml
      500:
        body:
          application/json:
            type: coreLib.errorResponseType
            examples: !include exchange_modules/9401a589-a992-4678-9f6b-f2f639e22832/core-api-library/1.0.1/examples/api-server-failure-response-example.raml
  
  /{ID}:
    get:
      is: [coreLib.clientIdRequired,coreLib.needsCorrelationId]
      displayName: get customer data
      description: Get customer data by ID
      responses:
        200:
          body:
            type: dataTypeLib.customer
            examples: !include exchange_modules/9401a589-a992-4678-9f6b-f2f639e22832/core-api-library1/1.0.3/example/customerData-example.raml
        400:
          body:
            type: coreLib.errorResponseType
            examples: !include exchange_modules/9401a589-a992-4678-9f6b-f2f639e22832/core-api-library/1.0.1/examples/api-client-failure-response-example.raml
        500:
          body:
            type: coreLib.errorResponseType
            examples: !include exchange_modules/9401a589-a992-4678-9f6b-f2f639e22832/core-api-library/1.0.1/examples/api-server-failure-response-example.raml
    patch:
      is: [coreLib.clientIdRequired,coreLib.needsCorrelationId]
      displayName: update customer
      description: update customer detailsby using customer ID
      body:
        type: dataTypeLib.customer
        examples: !include exchange_modules/9401a589-a992-4678-9f6b-f2f639e22832/core-api-library1/1.0.3/example/customerData-example.raml
      responses:
        200:
          body:
            type: object
            example:
              {
                message: "customer Updated"
              }
        400:
          body:
            type: coreLib.errorResponseType
            examples: !include exchange_modules/9401a589-a992-4678-9f6b-f2f639e22832/core-api-library/1.0.1/examples/api-client-failure-response-example.raml
        500:
          body:
            type: coreLib.errorResponseType
            examples: !include exchange_modules/9401a589-a992-4678-9f6b-f2f639e22832/core-api-library/1.0.1/examples/api-server-failure-response-example.raml
    delete:
      is: [coreLib.clientIdRequired,coreLib.needsCorrelationId]
      displayName: Delete Customer
      description: To delete the customer details 
      responses:
        200:
          body:
            type: object
            example:
              {
                message: "Customer Deleted"
              }
    /order:
      post:
        is: [coreLib.clientIdRequired,coreLib.needsCorrelationId]
        displayName: create order
        description: create orders by the customer
        body:
          type: dataTypeLib.order
          examples: !include exchange_modules/9401a589-a992-4678-9f6b-f2f639e22832/core-api-library1/1.0.3/example/orderData-example.raml
        responses:
          200:
            body:
              type: object
              example:
                {
                  message: "Order Placed"
                }             
          400:
            body:
              type: coreLib.errorResponseType
              examples: !include exchange_modules/9401a589-a992-4678-9f6b-f2f639e22832/core-api-library/1.0.1/examples/api-client-failure-response-example.raml
          500:
            body:
              type: coreLib.errorResponseType
              examples: !include exchange_modules/9401a589-a992-4678-9f6b-f2f639e22832/core-api-library/1.0.1/examples/api-server-failure-response-example.raml
      /{OrderID}:
        get:
          is: [coreLib.clientIdRequired,coreLib.needsCorrelationId]
          displayName: get order data
          description: Get order data by ID
          responses:
            200:
              body:
                type: dataTypeLib.order
                examples: !include exchange_modules/9401a589-a992-4678-9f6b-f2f639e22832/core-api-library1/1.0.3/example/orderData-example.raml
            400:
              body:
                application/json:
                  type: coreLib.errorResponseType
                  examples: !include exchange_modules/9401a589-a992-4678-9f6b-f2f639e22832/core-api-library/1.0.1/examples/api-client-failure-response-example.raml
            500:
              body:
                application/json:
                  type: coreLib.errorResponseType
                  examples: !include exchange_modules/9401a589-a992-4678-9f6b-f2f639e22832/core-api-library/1.0.1/examples/api-server-failure-response-example.raml
        patch:
          is: [coreLib.clientIdRequired,coreLib.needsCorrelationId]
          displayName: update order
          description: update the misplaced order
          body:
            type: dataTypeLib.order
            examples: !include exchange_modules/9401a589-a992-4678-9f6b-f2f639e22832/core-api-library1/1.0.3/example/orderData-example.raml
          responses:
            200:
              body:
                type: object
                example:
                  {
                    message: "Order Updated"
                  }
            400:
              body:
                type: coreLib.errorResponseType
                examples: !include exchange_modules/9401a589-a992-4678-9f6b-f2f639e22832/core-api-library/1.0.1/examples/api-client-failure-response-example.raml
            500:
              body:
                type: coreLib.errorResponseType
                examples: !include exchange_modules/9401a589-a992-4678-9f6b-f2f639e22832/core-api-library/1.0.1/examples/api-server-failure-response-example.raml
        delete:
          is: [coreLib.clientIdRequired,coreLib.needsCorrelationId]
          responses:
            200:
              body:
                type: object
                example:
                  {
                    message: "Order Deleted"
                  }
            400:
              body:
                type: coreLib.errorResponseType
                example: !include /exchange_modules/9401a589-a992-4678-9f6b-f2f639e22832/core-api-library/1.0.1/examples/api-client-failure-response-example.raml
            500:
              body:
                type: coreLib.errorResponseType
                example: !include exchange_modules/9401a589-a992-4678-9f6b-f2f639e22832/core-api-library/1.0.1/examples/api-server-failure-response-example.raml
                    
                    
            